config/routes.rb
Rails.application.routes.draw do
 root 'static_pages#home'
 
  get 'site/about'
  get 'site/contact'
    
  
    
    get '/about' => 'site#about'
    get '/contact' => 'site#contact'
    get '/retros' => 'retros#index'
    get '/lists' => 'lists#index'
    get '/estimations' => 'estimations#index'
   # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

resources :contributors, only: [:create, :show] do
    resources :estimations, only: :create
  end

  resources :teams, only: [] do
    resource :votes, only: :create
  end
    
    
resources :lists do
        member do
             patch :move
            end
            end
  resources :cards do
        member do
        patch :move
        end
    end
   
    
  resources :retros do
      member do
          patch :move
      end
  end
  resources :ideas do
      member do
          patch :move
      end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/list.rb
class List < ApplicationRecord
    acts_as_list
    has_many :cards, ->{ order(position: :asc) }, dependent: :destroy
    validates :name, presence: true
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    before_action :set_list, only: [:show, :edit, :update, :destroy, :move]

  # GET /lists
  # GET /lists.json
  def index
      @lists = List.order(position: :asc)
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
          ActionCable.server.broadcast "board", { commit: 'addList', payload: render_to_string(:show, format: :json ) }
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  # MOVE
  def move
      @list.insert_at(list_params[:position].to_i)
    ActionCable.server.broadcast "board", { commit: 'moveList', payload: render_to_string(:show, format: :json) }
    render action: :show
      end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :position)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Task Board</h1>

<%= link_to 'New List', new_list_path %>
<hr/>
<div class="mt-3">
  <%= tag.div id: :boards, data: { lists: @lists.to_json(include: :cards) } %>
</div>
<hr/>
<table>
<thead>
    <tr>
    <th>Name</th>
    <th>Position</th>
    <th colspan="3"></th>
    </tr>
    </thead>
<tbody>
    <% @lists.each do |list| %>
    <tr>
    <td> <%= list.name %> </td>
        <td> <%= list.position %></td>
        <td> <%= link_to 'Show', list %> </td>
        <td> <%= link_to 'Edit', edit_list_path(list) %></td>
        <td> <%= link_to 'Destroy', list, method: :delete, data: {confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
    </tbody></table>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @list.position %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>