config/routes.rb
Rails.application.routes.draw do
 root 'static_pages#home'
 
  get 'site/about'
  get 'site/contact'
    
  
    
    get '/about' => 'site#about'
    get '/contact' => 'site#contact'
    get '/retros' => 'retros#index'
    get '/lists' => 'lists#index'
    get '/estimations' => 'estimations#index'
   # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

resources :contributors, only: [:create, :show] do
    resources :estimations, only: :create
  end

  resources :teams, only: [] do
    resource :votes, only: :create
  end
    
    
resources :lists do
        member do
             patch :move
            end
            end
  resources :cards do
        member do
        patch :move
        end
    end
   
    
  resources :retros do
      member do
          patch :move
      end
  end
  resources :ideas do
      member do
          patch :move
      end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/idea.rb
class Idea < ApplicationRecord
    acts_as_list scope: :retro
  belongs_to :retro
  validates :name, presence: true

 
  
  before_save :set_sentiment, if: :name_changed?
  
  scope :positive, ->{ where(sentiment: :positive) }
  scope :neutral, ->{ where(sentiment: :neutral) }
  scope :negative, ->{ where(sentiment: :negative) }
  
  def set_sentiment
       self.sentiment = $analyzer.sentiment(name)
       self.score = $analyzer.score(name)
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
          ActionCable.server.broadcast "ideaboard", { commit: 'addIdea', payload: render_to_string(:show, format: :json) }
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
          ActionCable.server.broadcast "ideaboard", { commit: 'addIdea', payload: render_to_string(:show, format: :json) }
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
 def move
      @idea.update(idea_params)
      ActionCable.server.broadcast "ideaboard", { commit: 'moveIdea', payload: render_to_string(:show, format: :json) }
      render action: :show
      end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:retro_id, :name, :position, :sentiment, :score)
    end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= form_with(model: idea, local: true) do |form| %>
  <% if idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :retro_id %>
    <%= form.text_field :retro_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.number_field :position %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ideas from Retrospective Board</h1>
<table class="table table-striped">

  <thead>
    <tr>
      
         <th scope="col">Idea</th>
         <th scope="col">Sentiment Analysis</th>
         <th scope="col">Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>
    <hr/>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        
        <td><%= idea.name %></td>
        <td><%= idea.sentiment %></td>
        <td><%= idea.score %></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Retro:</strong>
  <%= @idea.retro %>
</p>

<p>
  <strong>Name:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @idea.position %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>