config/routes.rb
Rails.application.routes.draw do
 root 'static_pages#home'
 
  get 'site/about'
  get 'site/contact'
    
  
    
    get '/about' => 'site#about'
    get '/contact' => 'site#contact'
    get '/retros' => 'retros#index'
    get '/lists' => 'lists#index'
    get '/estimations' => 'estimations#index'
   # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

resources :contributors, only: [:create, :show] do
    resources :estimations, only: :create
  end

  resources :teams, only: [] do
    resource :votes, only: :create
  end
    
    
resources :lists do
        member do
             patch :move
            end
            end
  resources :cards do
        member do
        patch :move
        end
    end
   
    
  resources :retros do
      member do
          patch :move
      end
  end
  resources :ideas do
      member do
          patch :move
      end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/retro.rb
class Retro < ApplicationRecord
    acts_as_list
    has_many :ideas, ->{ order(position: :asc) }, dependent: :destroy
    validates :name, presence: true
end

app/controllers/retros_controller.rb
class RetrosController < ApplicationController
  before_action :set_retro, only: [:show, :edit, :update, :destroy]

  # GET /retros
  # GET /retros.json
  def index
    @retros = Retro.all
  end

  # GET /retros/1
  # GET /retros/1.json
  def show
  end

  # GET /retros/new
  def new
    @retro = Retro.new
  end

  # GET /retros/1/edit
  def edit
  end

  # POST /retros
  # POST /retros.json
  def create
    @retro = Retro.new(retro_params)

    respond_to do |format|
      if @retro.save
          ActionCable.server.broadcast "ideaboard", { commit: 'addRetro', payload: render_to_string(:show, format: :json ) }
        format.html { redirect_to @retro, notice: 'Retro was successfully created.' }
        format.json { render :show, status: :created, location: @retro }
      else
        format.html { render :new }
        format.json { render json: @retro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /retros/1
  # PATCH/PUT /retros/1.json
  def update
    respond_to do |format|
      if @retro.update(retro_params)
        format.html { redirect_to @retro, notice: 'Retro was successfully updated.' }
        format.json { render :show, status: :ok, location: @retro }
      else
        format.html { render :edit }
        format.json { render json: @retro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /retros/1
  # DELETE /retros/1.json
  def destroy
    @retro.destroy
    respond_to do |format|
      format.html { redirect_to retros_url, notice: 'Retro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
    
    # MOVE
  def move
      @retro.insert_at(retro_params[:position].to_i)
    ActionCable.server.broadcast "ideaboard", { commit: 'moveRetro', payload: render_to_string(:show, format: :json) }
    render action: :show
      end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_retro
      @retro = Retro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def retro_params
      params.require(:retro).permit(:name, :position)
    end
end

app/helpers/retros_helper.rb
module RetrosHelper
end

app/views/retros/_form.html.erb
<%= form_with(model: retro, local: true) do |form| %>
  <% if retro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(retro.errors.count, "error") %> prohibited this retro from being saved:</h2>

      <ul>
      <% retro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.number_field :position %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/retros/edit.html.erb
<h1>Editing Retro</h1>

<%= render 'form', retro: @retro %>

<%= link_to 'Show', @retro %> |
<%= link_to 'Back', retros_path %>

app/views/retros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Retrospective Board</h1>

<%= link_to 'New Retro', new_retro_path %>
<hr/>
<div class="mt-3">
  <%= tag.div id: :ideaboards, data: { retros: @retros.to_json(include: :ideas) } %>
</div>

    <hr/>
<table>
  <thead>
    <tr>
  
      <th>Name</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @retros.each do |retro| %>
      <tr>
     
        <td><%= retro.name %></td>
        <td><%= retro.position %></td>
        <td><%= link_to 'Show', retro %></td>
        <td><%= link_to 'Edit', edit_retro_path(retro) %></td>
        <td><%= link_to 'Destroy', retro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/retros/new.html.erb
<h1>New Retro</h1>

<%= render 'form', retro: @retro %>

<%= link_to 'Back', retros_path %>

app/views/retros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @retro.name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @retro.position %>
</p>

<%= link_to 'Edit', edit_retro_path(@retro) %> |
<%= link_to 'Back', retros_path %>